CREATE DATABASE QLHS
USE QLHS
GO
CREATE TABLE HOCSINH
(
MaHocSinh nvarchar(10),
HoTen nvarchar (50),
GioiTinh nvarchar(3),
NgaySinh datetime,
DiaChi nvarchar(100),
Email nvarchar(100),
primary key (MaHocSinh)
)

CREATE TABLE MONHOC
(
MaMonHoc nvarchar(10),
TenMonHoc nvarchar(10),
primary key (MaMonHoc)
)

CREATE TABLE KHOILOP
(
MaKhoiLop nvarchar (10),
TenKhoiLop nvarchar(10),
primary key (MaKhoiLop)
)

CREATE TABLE HOCKI
(
MaHocKi nvarchar(10),
TenHocKi nvarchar(10),
primary key (MaHocKi)
)

CREATE TABLE DANHSACHLOP
(
MaLop nvarchar(10),
TenLop nvarchar(10),
SiSo int,
MaKhoiLop nvarchar(10),
primary key (MaLop)
)

CREATE TABLE CHITIETDSLOP
(
MaChiTietDSLop nvarchar(10),
MaLop nvarchar(10),
MaHocSinh nvarchar(10),
TBHocKi1 float,
TBHocKi2 float,
Primary key (MaChiTietDSLop)
)

CREATE TABLE BAOCAOTONGKETMON
(
MaBaoCaoMon nvarchar(10),
MaHocKi nvarchar(10),
MaLop nvarchar(10),
MaMon nvarchar(10),
SoLuongDatMon int,
TiLeDatMon float,
primary key (MaBaoCaoMon)
)

CREATE TABLE BAOCAOTONGKETHK
(
MaBaoCaoHK nvarchar(10),
MaHocKi nvarchar(10),
MaLop nvarchar(10),
SoLuongDat int,
TiLeDat float,
primary key (MaBaoCaoHK)
)

CREATE TABLE THAMSO
(
TuoiToiThieu int,
TuoiToiDa int,
SiSoToiDa int,
DiemDatMon float,
)

CREATE TABLE KETQUAHOCTAP
(
MaKetQua nvarchar(10),
MaChiTietDSLop nvarchar(10),
MaHocKi nvarchar(10),
DiemTBHocKi float,
primary key (MaKetQua)
)

CREATE TABLE BANGDIEM
(
MaBangDiem nvarchar(10),
MaHocSinh nvarchar(10),
MaMonHoc nvarchar(10),
Diem15phut float,
Diem1tiet float,
DiemCuoiKi float,
primary key (MaBangDiem)
)
-- HOCSINH & CHITIETDANHSACHHS
ALTER TABLE CHITIETDSLOP
ADD CONSTRAINT FK_CHITTIET_HOCSINH
FOREIGN KEY (MaHocSinh)
REFERENCES HOCSINH (MaHocSinh)

ALTER TABLE CHITIETDSLOP
ADD CONSTRAINT FK_CHITTIET_DSLOP
FOREIGN KEY (MaLop)
REFERENCES DANHSACHLOP (MaLop)
-- DANHSACHLOP & KHOILOP
ALTER TABLE DANHSACHLOP
ADD CONSTRAINT FK_DANHSACHLOP_KHOILOP
FOREIGN KEY (MaKhoiLop)
REFERENCES KHOILOP (MaKhoiLop)

-- BANGDIEM & MONHOC
ALTER TABLE BANGDIEM
ADD CONSTRAINT FK_BANGDIEM_MONHOC
FOREIGN KEY (MaMonHoc)
REFERENCES MONHOC (MaMonHoc)
-- BANGDIEM & HOCSINH
ALTER TABLE BANGDIEM
ADD CONSTRAINT FK_BANGDIEM_HOCSINH
FOREIGN KEY (MaHocSinh)
REFERENCES HOCSINH (MaHocSinh)

-- KETQUAHOCTAP & CHITIETDSLOP
ALTER TABLE KETQUAHOCTAP
ADD CONSTRAINT FK_KETQUAHOCTAP_CHITIETDSLOP
FOREIGN KEY (MaChiTietDSLop)
REFERENCES CHITIETDSLOP (MaChiTietDSLop)

--HOCKY & KETQUAHOCTAP
ALTER TABLE KETQUAHOCTAP
ADD CONSTRAINT FK_KETQUAHOCTAP_HOCKY
FOREIGN KEY (MaHocKi)
REFERENCES HOCKI (MaHocKi)

--HOCKY & BAOCAOKETTHUCMON
ALTER TABLE BAOCAOTONGKETMON
ADD CONSTRAINT FK_BAOCAOTONGKETMON_HOCKY
FOREIGN KEY (MaHocKi)
REFERENCES HOCKI (MaHocKi)

--HOCKY & BAOCAOTONGKETHK
ALTER TABLE BAOCAOTONGKETHK
ADD CONSTRAINT FK_BAOCAOTONGKETHK_HOCKY
FOREIGN KEY (MaHocKi)
REFERENCES HOCKI (MaHocKi)

