use QLHS
go

alter PROC DSLOP 
AS
BEGIN
	
	SELECT HS.MaHocSinh, HS.HoTen, KL.TenKhoiLop, DSL.TenLop, DSL.SiSo
	FROM HOCSINH HS, KHOILOP KL, CHITIETDSLOP CTDSL, DANHSACHLOP DSL
	WHERE HS.MaHocSinh = CTDSL.MaHocSinh AND CTDSL.MaLop = DSL.MaLop AND DSL.MaKhoiLop = KL.MaKhoiLop
END

EXEC dbo.DSLOP
 go
--------------Tìm kiếm bằng MaHocSinh trong lớp--------------
ALTER PROC TIMHSBANGMA (@MaHocSinh nvarchar(10))
AS
BEGIN
	
	SELECT HS.MaHocSinh, HS.HoTen, KL.TenKhoiLop, DSL.TenLop
	FROM HOCSINH HS, KHOILOP KL, CHITIETDSLOP CTDSL, DANHSACHLOP DSL
	WHERE HS.MaHocSinh = @MaHocSinh  AND HS.MaHocSinh = CTDSL.MaHocSinh AND CTDSL.MaLop = DSL.MaLop AND DSL.MaKhoiLop = KL.MaKhoiLop
END

EXEC dbo.TIMHSBANGMA hs1

--------------------
SELECT * FROM HOCSINH
SELECT * FROM CHITIETDSLOP
SELECT * FROM DANHSACHLOP
SELECT * FROM KHOILOP