use QLHS

alter PROC DSLOP 
AS
BEGIN
	
	SELECT HS.MaHocSinh, HS.HoTen, KL.TenKhoiLop, DSL.TenLop, DSL.SiSo
	FROM HOCSINH HS, KHOILOP KL, CHITIETDSLOP CTDSL, DANHSACHLOP DSL
	WHERE HS.MaHocSinh = CTDSL.MaHocSinh AND CTDSL.MaLop = DSL.MaLop AND DSL.MaKhoiLop = KL.MaKhoiLop
END

EXEC dbO.DSLOP

SELECT * FROM HOCSINH
SELECT * FROM CHITIETDSLOP
SELECT * FROM DANHSACHLOP
SELECT * FROM KHOILOP