use QLHS
go

alter PROC DSLOP 
AS
BEGIN
	
	SELECT HS.MaHocSinh, HS.HoTen, KL.TenKhoiLop, DSL.TenLop
	FROM HOCSINH HS, KHOILOP KL, CHITIETDSLOP CTDSL, DANHSACHLOP DSL
	WHERE HS.MaHocSinh = CTDSL.MaHocSinh AND CTDSL.MaLop = DSL.MaLop AND DSL.MaKhoiLop = KL.MaKhoiLop
END

EXEC dbo.DSLOP
 go
--------------Tìm kiếm bằng MaHocSinh trong lớp--------------
ALTER PROC TIMHSBANGMA (@MaHocSinh nvarchar(10))
AS
BEGIN
	
	SELECT HS.MaHocSinh, HS.HoTen, HS.NgaySinh
	FROM HOCSINH HS, CHITIETDSLOP CTDSL
	WHERE HS.MaHocSinh = @MaHocSinh  AND HS.MaHocSinh = CTDSL.MaHocSinh
END

EXEC dbo.TIMHSBANGMA hs1
GO
--------------------
ALTER PROC ThemHSVaoLop (@TenLop nvarchar (10))
AS
BEGIN
DECLARE @MaLop nvarchar(10)
SELECT DSL.MaLop
	FROM DANHSACHLOP DSL, CHITIETDSLOP CTDSL
	WHERE DSL.TenLop = '10A1'
INSERT INTO CHITIETDSLOP(MaLop) VALUES ( '@MaLop')
END

exec dbo.ThemHSVaoLop '10A1'
SELECT * FROM HOCSINH
SELECT * FROM CHITIETDSLOP
SELECT * FROM DANHSACHLOP
SELECT * FROM KHOILOP

---------------------------
SELECT * FROM BANGDIEM
SELECT * FROM MONHOC
select * from KETQUAHOCTAP
select * from hocki
select * from BAOCAOTONGKETHK
select * from BAOCAOTONGKETMON
select * from THAMSO